### PR TITLE
CD-183087 master: upgrade librdkafka to release 1.2.2-RC1

### PR DESCRIPTION
**Pull request by abdollar**
- [x] @johnny-lai 

https://coupadev.atlassian.net/browse/CD-183087 - Upgrade librdkafka to the latest.

- Upgrade librdkafka to release 1.2.2-RC1
- Includes the timespec_get fix for MacOSX10.15.sdk for development.
- Added comments on where to find the checksum.
- I froze the constants to keep my local rubocop quiet.

### CODE REVIEW

**Comment by johnny-lai** [comment]
I think there are test failures?
https://travis-ci.org/coupa/rdkafka-ruby/jobs/633900162?utm_medium=notification&utm_source=github_status
```
  #seek
861    should raise an error when seeking fails
862    subscription
863      works when a partition is paused
864      allows skipping messages (FAILED - 1)
```

For the `No output has been received in the last 10m0s`, I think I usually rerun

**Comment by abdollar** [comment]
@johnny-lai changed to 1.2.2-RC1 which works for development.

**Comment by johnny-lai** [comment]
lgtm

**Comment by abdollar** [comment]
[lockit v4.9.2] merged via Lockit CLI on 2020-01-07 17:00:17.337793 -0800 PST m=+6.428419474

**Pull request merged**
