### PR TITLE
CD-217661 Add Consumer#join_state

### PR DESCRIPTION
**Pull request by johnny-lai**
* Provides a way to get the consumer's current join state

- [x] @abdulchaudhrycoupa 
- [x] @johnwu96822

### CODE REVIEW

**Comment by johnwu96822** [comment]
Why does abdollar become abdulchaudhrycoupa?

**Comment by johnwu96822** [comment]
👍

**Review by abdulchaudhrycoupa — APPROVED** [review]

**Comment by johnny-lai** [comment]
Amended commit to get Travis to rerun

**Comment by johnny-lai** [comment]
[lockit v4.9.3] merged via Lockit CLI on 2020-10-07 14:56:05.644802 -0700 PDT m=+5.381714675

**Pull request merged**
